blank_issues_enabled: true
contact_links:
  - name: Discussions / Ideas
    url: https://github.com/Stijnman/competitor_researcher/discussions
    about: Please use discussions for open-ended ideas and questions.
